[project]
name = "devtrack"
version = "0.1.0"
description = "Devtrack is an application to track dev tasks."
readme = "README.md"
authors = [
    { name = "pstrings", email = "masuya444@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.52.4",
]

[project.scripts]
devtrack = "devtrack:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
